apiVersion: 1

datasources:
  - name: ChordJobsAPI
    type: yesoreyeram-infinity-datasource
    uid: infinity-chord
    access: proxy
    url: http://host.docker.internal:5005
    isDefault: false
    editable: false
    jsonData:
      allowed_hosts:
        - http://host.docker.internal:5005
        - http://host.docker.internal:5006
        - http://host.docker.internal:5007
