# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api import task_service_pb2 as api_dot_task__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/task_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTask = channel.unary_unary(
                '/distributedchord.tasks.v1.TaskService/RegisterTask',
                request_serializer=api_dot_task__service__pb2.RegisterTaskRequest.SerializeToString,
                response_deserializer=api_dot_task__service__pb2.RegisterTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/distributedchord.tasks.v1.TaskService/GetTask',
                request_serializer=api_dot_task__service__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=api_dot_task__service__pb2.GetTaskResponse.FromString,
                _registered_method=True)
        self.DeregisterTask = channel.unary_unary(
                '/distributedchord.tasks.v1.TaskService/DeregisterTask',
                request_serializer=api_dot_task__service__pb2.DeregisterTaskRequest.SerializeToString,
                response_deserializer=api_dot_task__service__pb2.DeregisterTaskResponse.FromString,
                _registered_method=True)
        self.QueryTasks = channel.unary_unary(
                '/distributedchord.tasks.v1.TaskService/QueryTasks',
                request_serializer=api_dot_task__service__pb2.QueryTasksRequest.SerializeToString,
                response_deserializer=api_dot_task__service__pb2.QueryTasksResponse.FromString,
                _registered_method=True)
        self.LookupTaskOwner = channel.unary_unary(
                '/distributedchord.tasks.v1.TaskService/LookupTaskOwner',
                request_serializer=api_dot_task__service__pb2.LookupTaskOwnerRequest.SerializeToString,
                response_deserializer=api_dot_task__service__pb2.LookupTaskOwnerResponse.FromString,
                _registered_method=True)
        self.GetNodeInfo = channel.unary_unary(
                '/distributedchord.tasks.v1.TaskService/GetNodeInfo',
                request_serializer=api_dot_task__service__pb2.GetNodeInfoRequest.SerializeToString,
                response_deserializer=api_dot_task__service__pb2.GetNodeInfoResponse.FromString,
                _registered_method=True)


class TaskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupTaskOwner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTask,
                    request_deserializer=api_dot_task__service__pb2.RegisterTaskRequest.FromString,
                    response_serializer=api_dot_task__service__pb2.RegisterTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=api_dot_task__service__pb2.GetTaskRequest.FromString,
                    response_serializer=api_dot_task__service__pb2.GetTaskResponse.SerializeToString,
            ),
            'DeregisterTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterTask,
                    request_deserializer=api_dot_task__service__pb2.DeregisterTaskRequest.FromString,
                    response_serializer=api_dot_task__service__pb2.DeregisterTaskResponse.SerializeToString,
            ),
            'QueryTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTasks,
                    request_deserializer=api_dot_task__service__pb2.QueryTasksRequest.FromString,
                    response_serializer=api_dot_task__service__pb2.QueryTasksResponse.SerializeToString,
            ),
            'LookupTaskOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupTaskOwner,
                    request_deserializer=api_dot_task__service__pb2.LookupTaskOwnerRequest.FromString,
                    response_serializer=api_dot_task__service__pb2.LookupTaskOwnerResponse.SerializeToString,
            ),
            'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeInfo,
                    request_deserializer=api_dot_task__service__pb2.GetNodeInfoRequest.FromString,
                    response_serializer=api_dot_task__service__pb2.GetNodeInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributedchord.tasks.v1.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributedchord.tasks.v1.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedchord.tasks.v1.TaskService/RegisterTask',
            api_dot_task__service__pb2.RegisterTaskRequest.SerializeToString,
            api_dot_task__service__pb2.RegisterTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedchord.tasks.v1.TaskService/GetTask',
            api_dot_task__service__pb2.GetTaskRequest.SerializeToString,
            api_dot_task__service__pb2.GetTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedchord.tasks.v1.TaskService/DeregisterTask',
            api_dot_task__service__pb2.DeregisterTaskRequest.SerializeToString,
            api_dot_task__service__pb2.DeregisterTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedchord.tasks.v1.TaskService/QueryTasks',
            api_dot_task__service__pb2.QueryTasksRequest.SerializeToString,
            api_dot_task__service__pb2.QueryTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupTaskOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedchord.tasks.v1.TaskService/LookupTaskOwner',
            api_dot_task__service__pb2.LookupTaskOwnerRequest.SerializeToString,
            api_dot_task__service__pb2.LookupTaskOwnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedchord.tasks.v1.TaskService/GetNodeInfo',
            api_dot_task__service__pb2.GetNodeInfoRequest.SerializeToString,
            api_dot_task__service__pb2.GetNodeInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class InternalReplicationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReplicateTask = channel.unary_unary(
                '/distributedchord.tasks.v1.InternalReplicationService/ReplicateTask',
                request_serializer=api_dot_task__service__pb2.ReplicateTaskRequest.SerializeToString,
                response_deserializer=api_dot_task__service__pb2.ReplicateTaskResponse.FromString,
                _registered_method=True)


class InternalReplicationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReplicateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalReplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReplicateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateTask,
                    request_deserializer=api_dot_task__service__pb2.ReplicateTaskRequest.FromString,
                    response_serializer=api_dot_task__service__pb2.ReplicateTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributedchord.tasks.v1.InternalReplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributedchord.tasks.v1.InternalReplicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InternalReplicationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReplicateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedchord.tasks.v1.InternalReplicationService/ReplicateTask',
            api_dot_task__service__pb2.ReplicateTaskRequest.SerializeToString,
            api_dot_task__service__pb2.ReplicateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
